### ISSUE TITLE
Suggestion: use generated gitignore

### ISSUE THREAD

**Issue by flanaras** [sujata5538/adventofcode2021#1]
In your current .gitignore do you need to include `.git` and `adventofcode2021`?

There's a website (not only one) that generates gitignore files for different languages, IDEs, etc.. The one I have been using is https://www.toptal.com/developers/gitignore. I think it's does a nice job.

**Comment by sujata5538** [comment]
Thanks for the suggestion. It's resolved now :-) 
https://github.com/sujata5538/adventofcode2021/blob/main/.gitignore
